INSERT INTO TEAMS VALUES ('ORL', 'Orlando', 'Magic');
INSERT INTO TEAMS VALUES ('TOR', 'Toronto', 'Raptors');
INSERT INTO TEAMS VALUES ('CLE', 'Cleveland', 'Cavaliers');
INSERT INTO TEAMS VALUES ('MIN', 'Minnesota', 'Timberwolves');
INSERT INTO TEAMS VALUES ('NYK', 'New York', 'Knicks');
INSERT INTO TEAMS VALUES ('PHX', 'Phoenix', 'Suns');
INSERT INTO TEAMS VALUES ('SAC', 'Sacramento', 'Kings');
INSERT INTO TEAMS VALUES ('SAS', 'San Antonio', 'Spurs');
INSERT INTO TEAMS VALUES ('BKN', 'Brooklyn', 'Nets');
INSERT INTO TEAMS VALUES ('IND', 'Indiana', 'Pacers');
INSERT INTO TEAMS VALUES ('UTA', 'Utah', 'Jazz');
INSERT INTO TEAMS VALUES ('CHA', 'Charlotte', 'Hornets');
INSERT INTO TEAMS VALUES ('CHI', 'Chicago', 'Bulls');
INSERT INTO TEAMS VALUES ('PHI', 'Philadelphia', '76ers');
INSERT INTO TEAMS VALUES ('DAL', 'Dallas', 'Mavericks');
INSERT INTO TEAMS VALUES ('GSW', 'Golden State', 'Warriors');
INSERT INTO TEAMS VALUES ('DEN', 'Denver', 'Nuggets');
INSERT INTO TEAMS VALUES ('LAC', 'Los Angeles', 'Clippers');
INSERT INTO TEAMS VALUES ('BOS', 'Boston', 'Celtics');
INSERT INTO TEAMS VALUES ('MEM', 'Memphis', 'Grizzlies');
INSERT INTO TEAMS VALUES ('DET', 'Detroit', 'Pistons');
INSERT INTO TEAMS VALUES ('LAL', 'Los Angeles', 'Lakers');
INSERT INTO TEAMS VALUES ('MIA', 'Miami', 'Heat');
INSERT INTO TEAMS VALUES ('POR', 'Portland', 'Trail Blazers');
INSERT INTO TEAMS VALUES ('ATL', 'Atlanta', 'Hawks');
INSERT INTO TEAMS VALUES ('OKC', 'Oklahoma City', 'Thunder');
INSERT INTO TEAMS VALUES ('MIL', 'Milwaukee', 'Bucks');
INSERT INTO TEAMS VALUES ('HOU', 'Houston', 'Rockets');
INSERT INTO TEAMS VALUES ('NOP', 'New Orleans', 'Pelicans');
INSERT INTO TEAMS VALUES ('WAS', 'Washington', 'Wizards');
